<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="http://localhost/velo/produits">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/v/bs5/dt-1.13.4/r-2.4.1/datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="./public/base.css">
    <title>velo</title>
</head>



<body>
    <h1 align=center>Velo sccuderia pedale </h1>
    <h2 align=center>Connexion</h2>

    <form class="admin" action="admin/login" method="post">
        <div class="mb-2">
            <label for="pseudo" class="form-label">Pseudo</label>
            <i class="fa-solid fa-user"></i>
            <input type="pseudo" class="form-control" id="pseudo" name="pseudo">
            <div id="pseudo" class="form-text"></div>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label"></i> Mot de pass</label>
            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
            <input type=" password" class="form-control" id="password" name="password">

        </div>

        <button type="submit" name="submit" class="btn btn-primary">se connecter</button>
    </form>

    <?php
    if (isset($error)) {
        echo $error;
    } else {
        echo "";
    }

    ?>

</body>

</html>