




<h1 align=center>Entrez vos produits</h1>
<form align=center class="form-control" action="produits/ajoutProduits" method="post">

    <label for="name">Nom du produit</label><br><br>
    <input type="text" name="nom" id=""><br><br>

    <label for="name">reference du produit</label><br><br>
    <input type="text" name="reference" id=""><br><br>

    <label for="name">prix du produit</label><br><br>
    <input type="number" name="price_ht" id=""><br><br>

    <label for="name">stock du produit</label><br><br>
    <input type="text" name="stock" id=""><br><br>

    <label for="name">alerte </label><br><br>
    <input type="text" name="alerte" id=""><br><br>

    <button class="btn btn-success" type="submit" name="submit">valider</button>

</form>