<!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>

</head>


<body>
        <h1 align=center><i class="fa-solid fa-users"></i> Formulaire des clients</h1>

        <form class="table table-info table-dark table-striped mx-auto border red-border " action="formulaire/ajoutClient" method="post">

                <label for="nom">Nom :</label><br><br>
                <input type="text" name="name" id=""><br><br>

                <label for="prenom">Prenom:</label><br><br>
                <input type="prenom" name="prenom" id=""><br><br>

                <label for="email">Email:</label><br><br><br>
                <input type="email" name="email" id=""><br><br>

                <label for="tel">telephone</label><br><br>
                <input type="tel" name="tel" id=""><br><br>

                <label for="adress1">Adresse1 :</label><br><br>
                <input type="text" name="adresse1" id=""><br><br>

                <input type="text" name="adresse2" id=""><br><br>
                <label for="adress2">adresse 2:</label><br><br>

                <input type="number" name="code_postal" id=""><br><br>
                <label for="code_postal">code postal:</label> <br><br>

                <input type="submit" name='submit' value="valider">




        </form>

</body>